"""5

Revision ID: a3d1418e69d2
Revises: e18ed5205776
Create Date: 2024-11-10 17:48:49.575061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d1418e69d2'
down_revision = 'e18ed5205776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DeliveryRoute', schema=None) as batch_op:
        batch_op.alter_column('StartTime',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('EndTime',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)

    with op.batch_alter_table('Payment', schema=None) as batch_op:
        batch_op.alter_column('PaymentDate',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Payment', schema=None) as batch_op:
        batch_op.alter_column('PaymentDate',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('DeliveryRoute', schema=None) as batch_op:
        batch_op.alter_column('EndTime',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('StartTime',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
