"""3

Revision ID: bd06af6b83a7
Revises: 30cf4c88acb5
Create Date: 2024-11-10 17:04:38.603510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd06af6b83a7'
down_revision = '30cf4c88acb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Courier', schema=None) as batch_op:
        batch_op.alter_column('BirthDate',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Courier', schema=None) as batch_op:
        batch_op.alter_column('BirthDate',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
